website/views.py
import io
import uuid
from datetime import datetime

from flask import Blueprint, render_template, request, flash, redirect, current_app, url_for, abort
from flask_login import current_user, login_required
from sqlalchemy import or_

from .extenctions import db
from .models import Products, Brand, Comments, ProductPhotos, User
from filestack import Client
from sqlalchemy.sql.expression import func

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
def home():
    products = Products.query.order_by(func.random()).limit(10).all()
    products = [products[i:i + 3] for i in range(0, len(products), 3)]
    return render_template("home.html", user=current_user, products=products)


@views.route("/my_products", methods=['GET', 'POST'])
@login_required
def my_products():
    page = request.args.get('page', 1, type=int)
    products = Products.query.filter_by(id_user=current_user.get_id()).join(Brand,
                                                                            Products.id_brand == Brand.id).add_columns(
        Products.name, Products.description, Brand.name).paginate(page=page, per_page=12)

    return render_template("my_products.html", user=current_user, products=products, page=page)


@views.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():
    brands = Brand.query.all()
    if request.method == 'POST':
        name_product = request.form.get('name')
        brand = request.form.get('brand')
        description = request.form.get('description')
        barcode = request.form.get('barcode')
        image = request.files['upload']

        product = Products(name=name_product, id_brand=brand, description=description, id_user=current_user.get_id(),
                           barcode=barcode, rating=0)
        db.session.add(product)
        db.session.commit()

        if image:
            if image.filename == '':
                flash('Choose file', 'error')
                return redirect(request.url)

            elif not allowed_file(image.filename):
                flash("Bad filename extencions!", 'error')
                return redirect(request.url)

            else:

                ext = image.mimetype.split('/')[1]
                name = str(uuid.uuid4())
                filename = name + "." + ext
                store_params = {
                    "filename": filename,
                    "mimetype": image.mimetype
                }
                client = Client(current_app.config['IMAGE_UPLOAD_API'])
                file = client.upload(file_obj=io.BytesIO(image.read()), store_params=store_params)
                photo = ProductPhotos(id_user=current_user.get_id(), id_product=product.id, photo=file.url,
                                      file_name=filename)
                product.photo = file.url
                db.session.add(photo, product)

                db.session.commit()
                flash("Product added", 'message')

        else:
            db.session.add(product)
            db.session.commit()
            flash("Product added without photo", 'message')

    return render_template("upload.html", brands=brands)


@views.route("/search", methods=['GET'])
def search():
    query = request.args.get('query', '')
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 12, type=int)
    sort = request.args.get('sort')
    sub = None
    if sort == 'rate_asc':
        sub = Products.rating.asc()
    elif sort == 'rate_desc':
        sub = Products.rating.desc()
    elif sort == 'alfa_asc':
        sub = Products.name.asc()
    elif sort == 'alfa_desc':
        sub = Products.name.desc()
    elif sort == 'date_asc':
        sub = Products.date.asc()
    elif sort == 'date_desc':
        sub = Products.date.desc()

    product = db.session.query(Brand.name,
                               Products.name,
                               Products.id,
                               Products.rating,
                               Products.photo
                               ).select_from(Products).join(Brand).filter(
        or_(Products.name.ilike(f'%{query}%'), Products.description.ilike(f'%{query}%'))).order_by(sub).paginate(
        page=page, per_page=per_page)

    return render_template("search.html", products=product, page=page, query=query,
                           per_page=per_page, sort=sort)


@views.route('/product/<int:id_product>', methods=["GET", "POST"])
def product(id_product):
    product = Products.query.filter_by(id=id_product).join(Brand, Products.id_brand == Brand.id).add_columns(
        Brand.name,
        Products.id).first_or_404()

    comments = Comments.query.filter_by(id_product=id_product).join(User, Comments.id_user == User.id).add_columns(
        User.nick).all()

    photos = ProductPhotos.query.filter_by(id_product=id_product).all()

    comment_added = False
    if current_user.is_authenticated:
        x = Comments.query.filter_by(id_user=current_user.get_id(), id_product=id_product).all()
        if x:
            comment_added = True

    if request.method == "POST" and not comment_added:
        stars = request.form.get("rate")
        comment = request.form.get("comment")
        if stars and comment:
            new_comment = Comments(id_user=current_user.get_id(),
                                   id_product=id_product,
                                   comment=comment,
                                   rating=stars)
            db.session.add(new_comment)
            db.session.commit()
        else:
            flash('Wypełnij obowiązkowe pola', 'error')
        return redirect(url_for("views.product", id_product=id_product))

    return render_template("product.html", user=current_user, product=product, comments=comments,
                           comment_added=comment_added, photos=photos, str=str)


@views.route("/delete/<int:id_comment>/<int:id_user>/<int:id_product>", methods=["GET", "POST"])
def delete(id_user, id_comment, id_product):
    if current_user.is_authenticated and current_user.get_id() == str(id_user):
        x = Comments.query.filter(Comments.id == id_comment and Comments.id_user == id_user).first_or_404()
        if x:
            db.session.delete(x)
            db.session.commit()
            flash("Komentarz usunięty", category="message")
            return redirect(url_for("views.product", id_product=id_product))

    return render_template("home.html", user=current_user)


@views.route("/user/<string:id_user>", methods=["GET", "POST"])
@login_required
def user(id_user):
    if current_user.is_authenticated and current_user.get_id() == str(id_user):
        info: User = User.query.filter_by(id=id_user).first_or_404()
        dni = (datetime.now() - info.data_rejestracji).days
        products_added = db.session.query(Products.photo, Brand.name, Products.name, Products.date).join(Brand).filter(
            Products.id_user == id_user)
    else:
        abort(403)
    return render_template("user.html", user=current_user, info=info, czas=dni, products=products_added)


def allowed_file(filename):
    if not '.' in filename:
        return False

    ext = filename.rsplit('.')[-1]

    if ext.lower() in current_app.config['IMAGE_EXTENSIONS']:
        return True
    else:
        return False

website/templates/base.html
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <script src={{ url_for('static', filename='assets/js/bootstrap.js') }}></script>


    {% block stylesheet %}{% endblock %}
    <title>{% block title %}Home{% endblock %}</title>
</head>

<body>

{% include 'include/navbar.html' %}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %} {% endfor %} {% endif %} {% endwith %}

    {% block content %} {% endblock %}
</body>

</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Rate the product{% endblock %}
{% block content %}
  <div class="container">
    <div class="row my-sm-3">
      <div class="col-sm-3 d-none d-sm-block">
        <img
          class="image-home"
          src="../static/assets/img/brand-reputation.svg"
          alt=""
        />
      </div>
      <div class="col-sm-6 align-self-end">
        <p class="fs-4 fw-bold text-center">Sprawdź opinie przed zakupem</p>
      </div>
      <div class="col-sm-3 p-5 d-none d-sm-block">
        <img
          class="image-home"
          src="../static/assets/img/complain.svg"
          alt=""
        />
      </div>
    </div>
    <div class="row justify-content-center my-3">
      <div class="col-sm-6 p-md-4 p-lg-5">
        <form class="d-flex search-main" action="/search">
          <input
            class="search-input form-control form-control-lg"
            type="search"
            placeholder="Search"
            aria-label="Search"
            name="query"
          />
          <button class="btn btn-outline-primary btn-lg" type="submit">
            <img src="../static/assets/img/icons/search.svg" alt="search" />
          </button>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3 my-3">
        <img
          class="image-home"
          src="../static/assets/img/giving-a-feedback.svg"
          alt=""
        />
      </div>
      <div class="col-sm-6 align-self-center my-3">
        <p class="fs-5 text-center">
          Podziel się swoją opinią na temat produktów dostępnych w popularnych
          sieciach handlowych. Zobacz opinie innych kupujących, czy warto kupić
          dany produkt i nie daj się naciąć.
        </p>
      </div>
      <div class="col-sm"></div>
    </div>

    <div class="row mt-5">
      <div
        id="carouselRecommenedProducts"
        class="carousel"
        data-bs-ride="carousel"
      >
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="card-group py-2 justify-content-evenly">
              {% for product in products[0] %}
                <div class="card border-violet-card mx-auto mx-sm-1 mx-md-2">
                  <div class="ratio ratio-4x3">
                    <img
                      class="card-img-top"
                      src="{{ product.photo | image_url }}"
                      crossorigin="anonymous"
                    />
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.rating }}</p>
                    <a
                      href="{{ url_for('views.product', id_product=product.id) }}"
                      class="btn btn-sm btn-primary"
                      >Idź do produktu</a
                    >
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>

          {% for products_arr in products[1:] %}
            <div class="carousel-item">
              <div class="card-group py-2 justify-content-evenly">
                {% for product in products_arr %}
                  <div class="card border-violet-card mx-auto mx-sm-1 mx-md-2">
                    <div class="ratio ratio-4x3">
                      <img
                        src="{{ product.photo | image_url }}"
                        class="card-img-top"
                        crossorigin="anonymous"
                        loading="lazy"
                      />
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">{{ product.rating }}</p>
                      <a
                        href="{{ url_for('views.product', id_product=product.id) }}"
                        class="btn btn-sm btn-primary"
                        >Idź do produktu</a
                      >
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>
        <button
          class="carousel-control-prev"
          type="button"
          data-bs-target="#carouselRecommenedProducts"
          data-bs-slide="prev"
        >
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button
          class="carousel-control-next"
          type="button"
          data-bs-target="#carouselRecommenedProducts"
          data-bs-slide="next"
        >
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.3.0/color-thief.umd.js"></script>
  <script src="{{ url_for('static', filename='main.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/js/get-color.js') }}"></script>

  <!-- <script src="{{ url_for('static', filename='main.js') }}"></script> -->
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <div class="container-lg">

        <div class="container p-3 justify-content-center">
            <div class="col-4 p-3 m-auto">
                <img class="image-home" src="../static/assets/img/login-in-violet.svg" alt=""/>
            </div>
            <div class="col-sm-6 p-3 m-auto">
                <form method="post">
                    <div class="input-group mb-2 login-input-group">
                        <span class="input-group-text"> <i class="bi bi-envelope"></i> </span>
                        <input class="form-control" type="email" id="email" name="email" placeholder="E-mail"/>
                    </div>
                    <div class="input-group mb-2 login-input-group">
                        <span class="input-group-text"> <i class="bi bi-key"></i> </span>
                        <input class="form-control" type="password" id="password1" name="password1"
                               placeholder="Password"/>
                    </div>
                    <button class="btn btn-outline-success me-auto" type="submit">
                        Login
                    </button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}
    

website/templates/my_products.html
{% extends "base.html" %} {% block title %}Products{% endblock %} {% block content %}
    <h3>Products</h3>
    <div class="row  justify-content-center">
        {% for product in products.items %}
            <div class="card">
                <div class="card-header">
                    Brand
                    {{ product[3] }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ product[1] }}</h5>
                    <p class="card-text">{{ product[2] }}</p>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

website/templates/product.html
{% extends "base.html" %}
{% block title %}Products{% endblock %}
{% block content %}
    <div class="container p-3">

        <div class="row border-violet-card justify-content-around p-4">
            <div class="col-sm-5">
                {% if photos %}
                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="{{ photos[0].photo }}" alt="First slide">
                            </div>
                            {% for photo in photos[1:] %}
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="{{ photo.photo }}" alt="First slide">
                                </div>
                            {% endfor %}
                        </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
                    </div>
                {% else %}

                    <img
                            class="image-product"
                            src="../static/assets/img/product_photo/Default.svg"
                            alt=""
                    />

                {% endif %}
            </div>
            <div class="col-sm-5">

                <p>Producent: &nbsp; {{ product[1] }}</p>

                <p>Nazwa: &nbsp;{{ product[0].name }}</p>

                <p class="card-text">{{ product[0].rating }}</p>

                <p>Opis: &nbsp; {{ product[0].description }}</p>

                <p>Data dodania: {{ product[0].date.strftime('%Y-%m-%d') }}</p>

                <p>Kod kreskowy: &nbsp; {{ product[0].barcode }}</p>
            </div>
        </div>



        {% if current_user.is_authenticated and comment_added == False %}

            <form class="row border-violet-card justify-content-around p-2 m-3" method="post">
                <div class="rate w-auto">
                    <input type="radio" id="star5" name="rate" value="5"/>
                    <label for="star5" title="text">5 stars</label>
                    <input type="radio" id="star4" name="rate" value="4"/>
                    <label for="star4" title="text">4 stars</label>
                    <input type="radio" id="star3" name="rate" value="3"/>
                    <label for="star3" title="text">3 stars</label>
                    <input type="radio" id="star2" name="rate" value="2"/>
                    <label for="star2" title="text">2 stars</label>
                    <input type="radio" id="star1" name="rate" value="1"/>
                    <label for="star1" title="text">1 star</label>
                </div>


                <div class="col-sm-6 mb-1">

                    <label for="comment">Komentarz: </label>
                    <textarea class="form-control" id="comment" name="comment" rows="3" placeholder="oceń  produkt"
                              required></textarea>

                </div>
                <div class=" align-self-center w-auto">
                    <button class="btn btn-outline-success" type="submit">Dodaj</button>
                    <button class="btn btn-outline-danger" type="reset">Anuluj</button>
                </div>


            </form>

        {% endif %}

        {% for comment in comments %}

            <div class="row border-violet-card justify-content-around p-2 m-3">
                <div class="col-sm-2">
                    <img
                            class="mb-1"
                            src="{{ 'https://avatars.dicebear.com/api/personas/'+comment[1]+'.svg' }}"
                            alt=""
                            width="50px"
                            height="50px"
                    />
                    <p class="mb-0 small fw-light">{{ comment[1] }}</p>
                    <p class="mb-0 small fw-lighter">{{ comment[0].date.strftime('%Y-%m-%d') }}</p>
                </div>
                <div class=" card-text w-auto align-self-center col-sm-2">
                    {{ comment[0].rating }}
                </div>
                <div class="col-sm-8 align-self-center text-center">
                    <p>{{ comment[0].comment }}</p>
                </div>

                {% if current_user.is_authenticated and user.get_id() == str(comment[0].id_user) %}
                    <a href=/delete/{{ comment[0].id }}/{{ comment[0].id_user }}/{{ comment[0].id_product }}>
                        <button class="btn btn-sm btn-red" type="button" name="del" id="delete">Usuń komentarz
                        </button>
                    </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

website/templates/search.html
{% extends "base.html" %} {% block title %}Products{% endblock %}
{%
  block
  content
%}
  <div class="container p-3 flex-column">
    <div class="d-flex mb-2">
      <h3>Products</h3>
      <div class="accordion ms-auto" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button
              class="accordion-button collapsed"
              type="button"
              data-bs-toggle="collapse"
              aria-expanded="false"
              data-bs-target="#collapseOne"
              aria-controls="collapseOne"
            >
              Sortuj
            </button>
          </h2>
          <div
            id="collapseOne"
            class="accordion-collapse collapse"
            aria-labelledby="headingOne"
            data-bs-parent="#accordionExample"
          >
            <div class="d-flex flex-column">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a
                    href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort='rate_asc') }}"
                  >
                    Ocena rosnąco</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort='rate_desc') }}"
                    >Ocena malejąco</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort='alfa_asc') }}"
                    >Alfabetycznie A-Z</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort='alfa_desc') }}"
                    >Alfabetycznie Z-A</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort='date_desc') }}"
                    >Najnowsze</a
                  >
                </li>
                <li class="nav-item">
                  <a
                    href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort='date_asc') }}"
                    >Najstarsze</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row justify-content-around">
      {%
        for (brand_name, product_name,product_id ,rating, photo) in
        products.items
      %}
        <div
          class="card border-violet-card mb-4 justify-content-between"
          style="width: 18rem"
        >
          <div class="ratio ratio-4x3">
            <img
              src="{{ photo | image_url }}"
              class="card-img-top"
              crossorigin="anonymous" 
              loading="lazy"
            />
          </div>
          <div class="card-body flex-grow-0">
            <h5 class="card-title">{{ brand_name }}, {{ product_name }}</h5>
            <p class="card-text">{{ rating }}</p>
            <a
              href="{{ url_for('views.product', id_product=product_id) }}"
              class="btn btn-sm btn-primary"
              >Show more</a
            >
          </div>
        </div> 
      {% endfor %}
    </div>
    <div class="p-1">
      <nav
        class="d-flex justify-content-center"
        aria-label="Page navigation example"
      >
        <ul class="pagination">
          {% for page_num in products.iter_pages() %}{% if page_num %}
            {%
              if page
              == page_num
            %}
              <li class="page-item active">
                <a
                  class="page-link"
                  href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort=sort) }}"
                  >{{ page_num }}</a
                >
              </li>
            {% else %}
              <li class="page-item">
                <a
                  class="page-link"
                  href="{{ url_for('views.search', page=page_num, query=query, per_page=per_page, sort=sort) }}"
                  >{{ page_num }}</a
                >
              </li>
            {% endif %}
          {% else %}
            ...
          {% endif %}{% endfor %}
        </ul>
      </nav>

      <form class="d-flex justify-content-center" id="pp" method="get">
        <select class="" id="per_page" name="per_page" form="pp">
          <!-- prettier-ignore -->
          <option value="6" {% if per_page == 6 %} selected {% endif %}> 6</option>
          <!-- prettier-ignore -->
          <option value="12" {% if per_page == 12 %}selected{% endif %}> 12</option>
          <!-- prettier-ignore -->
          <option value="24" {% if per_page == 24 %}selected{% endif %}> 24</option>
        </select>
        <button class="btn btn-outline-primary ms-2" type="submit">Sub</button>
      </form>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.3.0/color-thief.umd.js"></script>
  <script src="{{ url_for('static', filename='main.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/js/get-color.js') }}"></script>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}

    <div class="container p-3 justify-content-center">
        <div class="col-4 p-3 m-auto">
            <img class="image-home" src="../static/assets/img/login-in-violet.svg" alt=""/>
        </div>
        <form method="post">
            <div class="col-sm-6 p-3 m-auto">
                <div class="input-group mb-2 login-input-group">
                    <span class="input-group-text"> <i class="bi bi-envelope"></i> </span>
                    <input type="email" class="form-control" placeholder="E-mail" id="email"
                           name="email"/>
                </div>
                <div class="input-group mb-2 login-input-group">
                    <span class="input-group-text"> <i class="bi bi-at"></i> </span>
                    <input type="text" class="form-control" placeholder="nick" id="nick"
                           name="nick"/>
                </div>
                <div class="input-group mb-2 login-input-group">
                    <span class="input-group-text"> <i class="bi bi-person"></i> </span>
                    <input type="text" class="form-control" placeholder="Name" id="firstName"
                           name="firstName"/>
                </div>
                <div class="input-group mb-2 login-input-group">
                    <span class="input-group-text"> <i class="bi bi-key"></i> </span>
                    <input type="password" class="form-control" placeholder="Password" id="password1"
                           name="password1"/>
                </div>
                <div class="input-group mb-2 login-input-group">
                    <span class="input-group-text"> <i class="bi bi-key-fill"></i> </span>
                    <input type="password" class="form-control" placeholder="confirm password" id="password2"
                           name="password2"/>
                </div>
                <div class="d-flex justify-content-around">
                    <button class="btn btn-outline-success" type="submit">Sign up</button>

                    <button class="btn btn-outline-danger" type="cancel">Cancel</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
    

website/templates/upload.html
{% extends "base.html" %} {% block title %}Upload{% endblock %}

{% block content %}

    <div class="container p-3 justify-content-center">
        <form method="POST" enctype="multipart/form-data">

            <div class="col-4 m-auto">
                <img src="../static/assets/img/Folder.svg"/>
            </div>

            <div class="col-sm-6 p-3 m-auto">

                <div class="form-floating mb-3 upload-input-group">
                    <input type="text" class="form-control" name="name" id="name" placeholder="Nazwa produktu"
                           required/>
                    <label for="floatingInput">Nazwa produktu</label>
                </div>

                <div class="form-floating mb-3 upload-input-group">
                    <select class="form-select" id="floatingSelect" name="brand"
                            aria-label="Floating label select example" required>

                        <option selected></option>
                        {% for brand in brands %}
                            <option value="{{ brand.id }}">{{ brand.name }}</option>

                        {% endfor %}
                    </select>

                    <label for="floatingSelect">Producent</label>
                </div>

                <div class="form-floating mb-3 upload-input-group">
                    <textarea type="text" class="form-control" id="description" name="description"
                              placeholder="Opis" required></textarea>
                    <label for="description">Opis</label>
                </div>


                <div class="form-floating mb-3 upload-input-group">
                    <input type="number" class="form-control" id="barcode" name="barcode" placeholder="kod kreskowy"/>
                    <label for="name">kod kreskowy</label>
                </div>

                <div class="input-group mb-3 upload-input-group">
                    <label class="input-group-text" for="upload">Zdjęcie</label>
                    <input type="file" accept=".png, .jpg, .jpeg" class="form-control" id="upload" name="upload"
                           placeholder="załącz zdjęcie">

                </div>

                <div class="d-flex justify-content-around">
                    <button class="btn btn-outline-success" type="submit">Upload</button>
                    <button class="btn btn-outline-danger" type="reset">Reset</button>
                </div>

            </div>
        </form>
    </div>



{% endblock %}